// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: fs.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MkdirReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *MkdirReq) Reset() {
	*x = MkdirReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkdirReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReq) ProtoMessage() {}

func (x *MkdirReq) ProtoReflect() protoreflect.Message {
	mi := &file_fs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReq.ProtoReflect.Descriptor instead.
func (*MkdirReq) Descriptor() ([]byte, []int) {
	return file_fs_proto_rawDescGZIP(), []int{0}
}

func (x *MkdirReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirReq) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MkdirResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Ino  uint64 `protobuf:"varint,2,opt,name=ino,proto3" json:"ino,omitempty"`
	Gen  uint64 `protobuf:"varint,3,opt,name=gen,proto3" json:"gen,omitempty"`
}

func (x *MkdirResp) Reset() {
	*x = MkdirResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MkdirResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResp) ProtoMessage() {}

func (x *MkdirResp) ProtoReflect() protoreflect.Message {
	mi := &file_fs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResp.ProtoReflect.Descriptor instead.
func (*MkdirResp) Descriptor() ([]byte, []int) {
	return file_fs_proto_rawDescGZIP(), []int{1}
}

func (x *MkdirResp) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirResp) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *MkdirResp) GetGen() uint64 {
	if x != nil {
		return x.Gen
	}
	return 0
}

var File_fs_proto protoreflect.FileDescriptor

var file_fs_proto_rawDesc = []byte{
	0x0a, 0x08, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x08, 0x4d, 0x6b,
	0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f,
	0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x43,
	0x0a, 0x09, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x69, 0x6e,
	0x6f, 0x12, 0x10, 0x0a, 0x03, 0x67, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03,
	0x67, 0x65, 0x6e, 0x32, 0x26, 0x0a, 0x02, 0x46, 0x53, 0x12, 0x20, 0x0a, 0x05, 0x4d, 0x6b, 0x64,
	0x69, 0x72, 0x12, 0x09, 0x2e, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e,
	0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x69, 0x6e, 0x30, 0x36, 0x2f,
	0x4e, 0x65, 0x78, 0x75, 0x73, 0x46, 0x53, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_fs_proto_rawDescOnce sync.Once
	file_fs_proto_rawDescData = file_fs_proto_rawDesc
)

func file_fs_proto_rawDescGZIP() []byte {
	file_fs_proto_rawDescOnce.Do(func() {
		file_fs_proto_rawDescData = protoimpl.X.CompressGZIP(file_fs_proto_rawDescData)
	})
	return file_fs_proto_rawDescData
}

var file_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fs_proto_goTypes = []interface{}{
	(*MkdirReq)(nil),  // 0: MkdirReq
	(*MkdirResp)(nil), // 1: MkdirResp
}
var file_fs_proto_depIdxs = []int32{
	0, // 0: FS.Mkdir:input_type -> MkdirReq
	1, // 1: FS.Mkdir:output_type -> MkdirResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fs_proto_init() }
func file_fs_proto_init() {
	if File_fs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MkdirReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MkdirResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fs_proto_goTypes,
		DependencyIndexes: file_fs_proto_depIdxs,
		MessageInfos:      file_fs_proto_msgTypes,
	}.Build()
	File_fs_proto = out.File
	file_fs_proto_rawDesc = nil
	file_fs_proto_goTypes = nil
	file_fs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FSClient is the client API for FS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FSClient interface {
	Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*MkdirResp, error)
}

type fSClient struct {
	cc grpc.ClientConnInterface
}

func NewFSClient(cc grpc.ClientConnInterface) FSClient {
	return &fSClient{cc}
}

func (c *fSClient) Mkdir(ctx context.Context, in *MkdirReq, opts ...grpc.CallOption) (*MkdirResp, error) {
	out := new(MkdirResp)
	err := c.cc.Invoke(ctx, "/FS/Mkdir", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FSServer is the server API for FS service.
type FSServer interface {
	Mkdir(context.Context, *MkdirReq) (*MkdirResp, error)
}

// UnimplementedFSServer can be embedded to have forward compatible implementations.
type UnimplementedFSServer struct {
}

func (*UnimplementedFSServer) Mkdir(context.Context, *MkdirReq) (*MkdirResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mkdir not implemented")
}

func RegisterFSServer(s *grpc.Server, srv FSServer) {
	s.RegisterService(&_FS_serviceDesc, srv)
}

func _FS_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FSServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FS/Mkdir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FSServer).Mkdir(ctx, req.(*MkdirReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FS",
	HandlerType: (*FSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mkdir",
			Handler:    _FS_Mkdir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fs.proto",
}
